name: Github actions
on: [ push ]
  jobs:
    test:
      runs-on: ubuntu-latest
  steps:
  -run: echo "this job was automatically triggered by ${{github.event_name}}event."
  -run: run python main.py 